name: SyncFork

on:
  schedule:
    - cron: '0 8 * * *' # Daily at 0800 UTC/0000 PST 
  workflow_dispatch: # on button click

jobs:
  SyncFork:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.6
        with:
          owner: nix-community 
          base: master
          head: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PAT }}
          merge_method: rebase
          auto_approve: true

